services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valokichu-frontend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      # Add other environment variables if needed
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
