name: Auto Deploy to CyberPanel (Docker + Next.js)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: valokichu.com
          username: admin_valokichu
          password: admin_valokichu
          local-dir: ./
          server-dir: /public_html/frontend/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/.next/**
            **/Dockerfile
            **/docker-compose.yml

      - name: Rebuild & Restart Docker on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: rsmmonaem.me
          username: root
          password: RsmMonaem66@@
          script: |
            cd /home/valokichu.com/public_html/frontend
            docker-compose down
            docker-compose up -d --build
